export const Increment = 'increment'
export const Decrement = 'decrement'
export const Detail = 'Detail'
export const Show = 'show'
export const Hide = 'hide'
export const Nav1 = 'nav1'
export const Nav2 = 'nav2'
export const Add = 'add'